import React from "react";
import CustomCard from "../../Components/CustomCard/CustomCard";
import Header from "../../Components/Header/Header";
import Layout from "../../Components/Layout/Layout";
import Handicon from "../../Public/Images/icons/hand-wave.png"
import "./Dashboard.css";

const Dashboard = () => {
  return (
    <>
      <header>
        <title>GrandPMS | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </header>
      <Layout>
        <div className="dashboardMain">
          <div className="dashboard-left dashboardLeft">
            <Header
              className="headerSpace"
              title={
                <>
                  Hello, Akbar Ali{" "}
                  <span className="ms-3 d-inline-flex">
                    <img
                      src={Handicon}
                      className="welcomeHand"
                      width={28}
                      height={27}
                      alt="Hand Wave"
                    />
                  </span>
                </>
              }
            />
            
            {/* Custom-card */}
            <div className="card-display">
              <CustomCard label={"Sales"} amount={4029}/>
              <CustomCard label={"Total"} amount={4029}/>
              <CustomCard label={"New"} amount={4029}/>
            </div>
            {/* Custom-Card-End */}
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Dashboard;
