import {Col, Row, Space} from "antd";
import {useState} from "react";
import CustomButton from "../../Components/CustomButton/CustomButton";
import CustomInput from "../../Components/CustomInput/CustomInput";
import CustomInputPassword from "../../Components/CustomInputPassword/CustomInputPassword";
import Icons from "../../Logo/logo/logo.png"
import "./signin.css";

export default function SignIn() {
  const [emailID, setEmailID] = useState("");
  const [password, setPassword] = useState("");
  return (
    <>
      <header>
        <title>GrandPMS | Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
      </header>
      <Row className="signInWrapper" gutter={[0, 16]}>
        <Col md={10} xs={24} className="signInPoster">
          <svg xmlns="http://www.w3.org/2000/svg" width="511" height="308" viewBox="0 0 511 308" fill="none" className="signInPosterLogo">
            <path
              d="M379.561 181.661C378.351 181.719 377.544 180.451 378.178 179.413C378.927 178.203 379.619 176.934 380.311 175.608C399.334 140.56 428.733 130.645 447.18 128.051C450.004 127.647 451.734 124.707 450.696 122.056C450.235 120.96 449.37 120.038 448.275 119.635C405.041 102.341 368.609 122.402 359.155 128.454C358.117 129.088 356.849 128.339 356.849 127.129C356.907 125.63 356.907 124.131 356.907 122.574C356.503 82.9143 377.082 60.029 391.955 48.7304C394.261 46.9434 394.376 43.4847 392.07 41.6977L392.013 41.64C391.09 40.8907 389.822 40.4871 388.612 40.6601C342.668 46.7705 320.705 81.8767 315.459 91.6764C314.883 92.714 313.384 92.714 312.808 91.6764C312.116 90.4659 311.482 89.1977 310.732 87.9295C290.96 53.4574 297.762 23.3087 305.256 6.24559C306.409 3.59389 304.795 0.596317 301.97 0.0775059H301.912C300.702 -0.153077 299.492 0.135148 298.512 0.884541C261.272 28.6697 259.312 70.1169 259.485 81.3002C259.485 82.5107 258.16 83.2025 257.18 82.5684C256.027 81.8766 254.874 81.1273 253.663 80.4355C218.96 59.856 210.313 29.6498 208.584 11.1455C208.354 8.43616 205.587 6.64913 203.05 7.57146L202.993 7.62911C201.897 7.97499 201.033 8.78201 200.572 9.81963C181.203 52.6503 200.053 90.12 205.76 99.8621C206.336 100.9 205.587 102.168 204.376 102.11C202.877 101.995 201.09 101.88 199.822 101.88C159.297 100.554 137.219 78.0144 126.843 62.6231C125.344 60.3749 122.116 60.1443 120.329 62.1619L120.271 62.2195C119.522 63.0265 119.118 64.1218 119.233 65.2747C122.461 107.932 151.285 131.51 163.794 139.868C165.12 140.733 166.272 141.425 167.195 142.001C168.232 142.577 168.175 144.076 167.08 144.595C165.927 145.172 164.773 145.748 163.621 146.382C126.9 166.097 95.7717 156.701 79.458 148.4C77.3251 147.304 74.7309 148.573 74.2121 150.879C73.9815 151.858 74.1546 152.896 74.731 153.703C110.99 207.256 171.633 196.188 183.278 192.902C185.18 192.326 186.564 190.654 186.679 188.636C186.679 188.636 186.679 188.636 186.679 188.579C190.022 143.5 229.856 109.835 275.165 114.446C317.246 118.712 349.009 155.26 347.395 197.514C346.819 212.963 341.919 227.144 334.021 239.019C331.946 242.132 333.906 246.34 337.595 246.743C342.61 247.262 348.029 246.513 354.197 244.207C360.942 241.728 367.859 237.866 375.18 233.196C408.961 211.81 439.513 217.459 456.864 224.261C459.516 225.299 462.398 223.57 462.744 220.803V220.745C462.917 219.592 462.571 218.382 461.822 217.459C432.365 181.142 390.745 180.97 379.561 181.661Z"
              fill="black"
              fillOpacity="0.08"
            />
            <path
              d="M103.029 248.242C156.293 246.916 191.4 262.423 225.353 277.469C236.824 282.541 247.719 287.384 259.364 291.592C341.624 321.568 407.34 303.525 459.394 274.01C477.437 263.807 494.155 251.528 509.546 237.751C512.543 234.811 510.238 230.084 505.511 232.736C436.451 272.396 373.733 277.988 307.325 253.488C297.467 249.856 257.865 231.41 248.065 227.663C162.692 194.92 80.4318 205.815 1.74546 267.208C-1.71328 269.571 0.131152 276.373 5.83807 273.837C34.1997 260.117 67.6341 249.107 103.029 248.242Z"
              fill="black"
              fillOpacity="0.08"
            />
          </svg>
          <div className="signInText">
            <h2>Optimizing Task Workflow for better Productivity</h2>
            <p>This is a sample text, orginal content will update soon. This is a sample text, orginal content will update soon..</p>
          </div>
        </Col>
        <Col md={14} xs={24} className="signInForm">
          <div className="signInFormInner">
            <div className="logo">
              <img src={Icons} alt="Grand PMD" width={114} height={72} />
            </div>
            <h1 className="page-title">Sign In</h1>
            <p className="page-title-label text-gray mb-4 pb-2">Enter your credentials below to continue</p>
            <Space className="d-flex" direction="vertical" size={16}>
              <CustomInput dataTestId="emailID" id="emailID" label="Email ID" name="emailID" handleChange={(e) => setEmailID(e.target.value)} value={emailID} />
              <Space className="d-flex mb-2" direction="vertical">
                <CustomInputPassword
                  dataTestId="passwordID"
                  id="passwordID"
                  label="Password"
                  name="passwordID"
                  handleChange={(e) => setPassword(e.target.value)}
                  value={password}
                />
              </Space>
              <CustomButton
                className="w-100 justify-content-center"
                text="Sign In"
                size="large"
                type="dark"
                handleClick={(e) => {
                  console.log(e);
                }}
              />
            </Space>
          </div>
        </Col>
      </Row>
    </>
  );
}
