import { Avatar } from "antd";
import CustomLink from "../../Components/CustomLink/CustomLink";
import Layout from "../../Components/Layout/Layout";
import profile from "../../Components/public/Images/profile/profile-1.jpg"
import "./profile-settings.css";

export default function ProfileSettings() {
  const aboutDetailsContains = [
    {
      aboutDetailsHead: "Reports to",
      aboutDetailsTitle: "Sajjad Ali",
    },
    {
      aboutDetailsHead: "Department",
      aboutDetailsTitle: "Delivery",
    },
    {
      aboutDetailsHead: "Phone",
      aboutDetailsTitle: "+995-445-551-4048",
    },
    {
      aboutDetailsHead: "Employee ID",
      aboutDetailsTitle: "GD44",
    },
    {
      aboutDetailsHead: "Email",
      aboutDetailsTitle: "akbarali@gmail.com",
    },
    {
      aboutDetailsHead: "Region",
      aboutDetailsTitle: "Bangalore",
    },
  ];
  
  return (
    <>
      <header>
        <title>GrandPMS | Profile Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </header>
      <Layout>
        <div className="space-32">
          <div className="profileSettings">
            <h1 className="page-title">Profile settings</h1>
            <p className="page-title-label space-bottom-32 mb-0">
              This is your profile details as per the organization
            </p>
            <div
              className={`d-flex align-items-center profileCardWrap userProfileDetails`}
            >
               <Avatar size={90} src={profile} />
              <div className="profileCardContains">
                <h3>Akbar Ali</h3>
                <p>Delivery manager</p>
                <CustomLink
                  href="#"
                  text="Change password request"
                  size="medium"
                  type="underline"
                />
              </div>
            </div>
            <div className={`space-top-32 aboutDetailsWrap`}>
              <h3 className="small-head">About you</h3>
              <div className={`profileCardWrap`}>
                <div className={`aboutDetailsRow`}>
                  {aboutDetailsContains.map((item, i) => (
                    <div className={`aboutDetailsCol`} key={i}>
                      <p className="text-gray fw-500 mb-2">
                        {item.aboutDetailsHead}
                      </p>
                      <span className="p fw-500">{item.aboutDetailsTitle}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
